# Global Framework Configuration
# This file contains framework-wide settings that apply to all projects

version: "1.0.0"
environment: "development"  # Options: development, staging, production

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/framework.log"
  
# API Keys and External Services
services:
  langsmith:
    api_key: "${LANGSMITH_API_KEY}"
    project_name: "ultimate_ai_architect"
    
# Default paths
paths:
  projects_dir: "projects/"
  templates_dir: "flowise_templates/"
  
# Framework behavior settings
settings:
  auto_save: true
  backup_frequency: 3600  # seconds
  max_history_size: 100  # number of history items to keep

# LLM Provider Configurations
llm_providers:
  # OpenRouter Configuration
  # Check OpenRouter docs for up-to-date model names: https://openrouter.ai/docs
  openrouter:
    # Framework uses OpenRouter dynamically and any valid model identifier from their documentation can be used
    enabled: true
    api_key_env: "OPENROUTER_API_KEY"
    api_base: "https://openrouter.ai/api/v1"
    default_model: "anthropic/claude-3-opus-20240229"  # Check OpenRouter documentation for current model names and versions
  
  # Google Gemini Configuration
  google_gemini:
    enabled: true
    api_key_env: "GOOGLE_API_KEY"
    default_model: "gemini-1.5-pro"
    available_models:
      - "gemini-1.5-pro"
      - "gemini-1.5-flash"
      - "gemini-pro"

# RouteLLM Configuration
routellm:
  default_strategy: "balanced"  # Options: balanced, cost_optimized, performance_optimized
  fallback_model: "openrouter.anthropic/claude-3-haiku-20240307"
  task_model_mapping:
    creative_writing: "openrouter.anthropic/claude-3-sonnet-20240229"
    code_generation: "openrouter.meta-llama/llama-3-70b-instruct"
    data_analysis: "google_gemini.gemini-1.5-pro"
    summarization: "google_gemini.gemini-1.5-flash"
    question_answering: "openrouter.anthropic/claude-3-haiku-20240307"
    chat: "openrouter.mistralai/mistral-medium-latest"
